version: "3"

services:
  backend:
    container_name: "backend-app"
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    restart: unless-stopped

  frontend:
    container_name: "frontend-app"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    restart: unless-stopped
    depends_on:
      - backend
